if(VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO org-ru/vmime
    REF v1.0.0
    SHA512 3989b5b72f2aa2d7395088981b2b12bd0c31117d73fa47752c4b58ee8e0b6f56448f3ef6f0683ab57e8a306a526bc620f0b0335594f7dfa2a5e716347ee44adc
    HEAD_REF master
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DVMIME_BUILD_SHARED_LIBRARY=OFF
        -DVMIME_BUILD_STATIC_LIBRARY=ON
        -DVMIME_HAVE_MESSAGING_PROTO_MAILDIR=OFF
        -DVMIME_HAVE_MESSAGING_PROTO_SENDMAIL=OFF
        -DVMIME_HAVE_MESSAGING_PROTO_SMTP=ON
        -DVMIME_HAVE_MESSAGING_PROTO_POP3=OFF
        -DVMIME_HAVE_MESSAGING_PROTO_IMAP=ON
        -DVMIME_HAVE_SASL_SUPPORT=OFF
        -DVMIME_HAVE_TLS_SUPPORT=ON
		-DVMIME_TLS_SUPPORT_LIB=openssl
        -DVMIME_BUILD_DOCUMENTATION=OFF
        -DVMIME_BUILD_TESTS=OFF
        -DVMIME_BUILD_SAMPLES=OFF
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(PACKAGE_NAME vmime-static CONFIG_PATH "lib/cmake/vmime")